### ISSUE TITLE
Support track selection via tags / extraInformation

### ISSUE THREAD

**Issue by AndreasVolkmann** [AndreasVolkmann/spotify-reddit#23]
`/r/indieheads` is a subreddit that doesn't use flairs and mainly relies on tags, which will be available as `extaInformation`.

It should be possible to define selection rules based on these tags.

**Comment by AndreasVolkmann** [comment]
syntax :
```yaml
playlists:
  - id: x
    ...
    tagFilter:
      # Tag must be equal
      includeExact:
        - Edit
      # Tag contains
      include:
        - FRESH
      # Tag must not be equal
      excludeExact:
        - Album
      # Tag must not include
      exclude: 
        - video
      

  

   
```
